config/routes.rb
Rails.application.routes.draw do

  get 'genres/show'
  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]
    
    resources :genres, only: [:show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'check'
        get 'complete'
      end
    end

    resources :addresses, except: [:new, :show]

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, except: [:destroy]

    resources :genres, except: [:destroy, :show, :new]

    resources :customers, except: [:destroy, :create, :new]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 11, minimum: 10}



  def own_adress_display
    "〒#{post_code} #{address}"
  end

  def full_name
    "#{last_name}#{first_name}"
  end






end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

 before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(5)
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer), notice: "顧客情報を更新しました。"

  end

   private



  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_admission)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12 mx-auto">

      <div class="row">
        <div class="col-4">
          <h4 style="background-color:#DCDCDC">　<%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h4>
        </div>
      </div>
      <br>

      <div class="row">
        <div class="col-md-4">
          <p>会員ID</p>
        </div>
        <div class="col-md-8 mb-3">
          <%= @customer.id %>
        </div>
      </div>

      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

      <div class="row">
        <div class="col-md-4">
          <p>氏名</p>
        </div>
        <div class="col-md-8">
          <div class="field">
            <%= f.text_field :last_name %>
            <%=f.text_field :first_name %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <p>フリガナ</p>
        </div>
        <div class="col-md-8">
          <div class="field">
            <%= f.text_field :last_name_kana %>
            <%= f.text_field :first_name_kana %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :post_code, "郵便番号" %>
        </div>
        <div class="col-md-8 mb-3">
          <div class="field">
            <%= f.text_field :post_code %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :address, "住所" %>
        </div>
        <div class="col-md-8 mb-3">
          <div class="field">
            <%= f.text_field :address, size: "50" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :phone_number, "電話番号" %>
        </div>
        <div class="col-md-8 mb-3">
          <div class="field">
            <%= f.text_field :phone_number %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :email, "メールアドレス" %>
        </div>
        <div class="col-md-8 mb-3">
          <div class="field">
            <%= f.email_field :email %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :is_admission, "会員ステータス" %>
        </div>
        <div class="col-md-8 mb-3">
          <div class="field">
            <%= f.radio_button :is_admission, false %>
            <%= f.label :is_admission, "有効" %>
            <%= f.radio_button :is_admission, true %>
            <%= f.label :is_admission,"退会" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 text-right">
            <%= f.submit "変更内容を保存", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      </div>
      </div>
    </div>
    <br>
    <br>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mx-auto">
    <br>
    <br>
    <div class="row">
          <div class="col-2">
            <h4 style="background-color:#DCDCDC">　会員一覧　　</h4>
          </div>
        </div>
    <br>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th style="height: 50px">会員ID</th>
          <th style="height: 50px">氏名</th>
          <th style="height: 50px">メールアドレス</th>
          <th style="height: 50px">ステータス</th>
        </tr>
      </thead>

      <% @customers.each do |customer| %>

      <tbody>
        <tr>
          <td style="height: 60px"><%= customer.id %></td>
          <td style="height: 60px"><%= link_to admin_customer_path(customer.id) do %>
                                   <%= customer.last_name + customer.first_name %>
                                   <% end %></td>
          <td style="height: 60px"><%= customer.email %></td>
          <td style="height: 60px"><% if customer.is_admission == true %>
                                    <strong class="text-secondary">退会</strong>
                                    <% elsif customer.is_admission == false %>
                                    <strong class="text-success">有効</strong>
                                    <% end %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    <br>
      <%= paginate @customers %>
    </div>
  </div>
</div>
<br>
<br>

app/views/admin/customers/show.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      

      <div class="row">
        <div class="col-4">
          <h4 style="background-color:#DCDCDC">　　<%= @customer.last_name + @customer.first_name %>さんの会員詳細</h4>
        </div>
      </div>

        <div class="col-md-12">
          <table class="table table-borderless">
            <thead>
              <tr>
                <td style="width: 40%">会員ID</td>
                <td style="width: 60%"><%= @customer.id %></td>
              </tr>
              <tr>
                <td  style="width: 40%">氏名</td>
                <td  style="width: 60%"><%= @customer.last_name + @customer.first_name %></td>
              </tr>
              <tr>
                <td style="width: 40%">フリガナ</td>
                <td style="width: 60%"><%= @customer.last_name_kana + @customer.first_name_kana %></td>
              </tr>
              <tr>
                <td style="width: 40%">郵便番号</td>
                <td style="width: 60%"><%= @customer.post_code %></td>
              </tr>
              <tr>
                <td style="width: 40%">住所</td>
                <td style="width: 60%"><%= @customer.address %></td>
              </tr>
              <tr>
                <td style="width: 40%">電話番号</td>
                <td style="width: 60%"><%= @customer.phone_number %></td>
              </tr>
              <tr>
                <td style="width: 40%">メールアドレス</td>
                <td style="width: 60%"><%= @customer.email %></td>
              </tr>
              <tr>
                <td style="width: 40%">会員ステータス</td>
                <td style="width: 60%"><% if @customer.is_admission == true %>
                                         <strong class="text-secondary">退会</strong>
                                       <% elsif @customer.is_admission == false %>
                                         <strong class="text-success">有効</strong>
                                       <% end %></td>
              </tr>
              <tr>
                <td></td>
                <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success mr-5" %>
                    <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-info" %>
                </td>
              </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
<br>
<br>