config/routes.rb
Rails.application.routes.draw do

  get 'genres/show'
  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]
    
    resources :genres, only: [:show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'check'
        get 'complete'
      end
    end

    resources :addresses, except: [:new, :show]

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, except: [:destroy]

    resources :genres, except: [:destroy, :show, :new]

    resources :customers, except: [:destroy, :create, :new]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items
  
  validates :name, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :customer_id, presence: true
  validates :payment_method, presence: true
  validates :total_price, presence: true
  validates :postage, presence: true
  validates :status, presence: true
  
  
  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {waiting_for_payment: 0, confirmed_payment: 1, making: 2, shipping_preparation: 3, shipped: 4}
  
  def order_address_display
    "〒#{post_code} #{address}"
  end
  
  def order_price
    self.postage + self.total_price
  end
  
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items.all
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items.all
    if @order.update(order_params)
      if @order.status == "confirmed_payment"
        @order_items.each do |order_item|
          order_item.update(making_status: 1)
        end
        redirect_to request.referer
      elsif @order.status == "shipped"
        redirect_to admin_path
      else
        redirect_to request.referer
      end
    else
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-8 px-5 px-sm-0">
      <h2>注文履歴詳細</h2>
      <table class="table">
        <tbody>
          <tr>
            <th><strong>購入者</strong></th>
            <th><%= @order.customer.full_name %></th>
          </tr>
          <tr>
            <th><strong>注文日</strong></th>
            <th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
          </tr>
          <tr>
            <th><strong>配送先</strong></th>
            <th><%= @order.order_address_display%><%= @order.name %></th>
          </tr>
          <tr>
            <th><strong>支払方法</strong></th>
            <th><%= @order.payment_method_i18n %></th>
          </tr>
          <tr>
            <th><strong>注文ステータス</strong></th>
            <th>
              <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert, selected: @order.status %>
                <%= f.submit '更新', class:'btn btn-success' %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-8 px-5 px-sm-0">
      <table class="table">
        <thread>
          <tr>
            <th><strong>商品名</strong></th>
            <th><strong>単価（税込）</strong></th>
            <th><strong>数量</strong></th>
            <th><strong>小計</strong></th>
            <th><strong>制作ステータス</strong></th>
          </tr>
        </thread>
        <tbody>
          <% @order_items.each do |order_item| %>
            <tr>
              <th><%= order_item.item.name %></th>
              <th><%= order_item.price%></th>
              <th><%= order_item.quantity %></th>
              <th><%= order_item.price * order_item.quantity %></th>
              <th>
                <%= form_with model: order_item, url: admin_order_order_item_path(@order.id, order_item.id) do |f| %>
                  <%= f.select :making_status, OrderItem.making_statuses_i18n.invert, selected: order_item.making_status %>
                  <%= f.submit '更新', class:'btn btn-success' %>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 px-sm-0">
      <table class="table">
        <tr>
          <th>商品合計</th>
          <td><%= @order.total_price.to_s + '円' %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage.to_s + '円' %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= @order.order_price.to_s %>円</th>
        </tr>
      </table>
    </div>
  </div>
</div>