config/routes.rb
Rails.application.routes.draw do

  get 'genres/show'
  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]
    
    resources :genres, only: [:show]

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'check'
        get 'complete'
      end
    end

    resources :addresses, except: [:new, :show]

  end

  namespace :admin do
    get '/' => 'homes#top'

    resources :items, except: [:destroy]

    resources :genres, except: [:destroy, :show, :new]

    resources :customers, except: [:destroy, :create, :new]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  validates :name, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  
  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 11, minimum: 10}



  def own_adress_display
    "〒#{post_code} #{address}"
  end

  def full_name
    "#{last_name}#{first_name}"
  end






end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items
  has_many :order_items
  belongs_to :genre
  has_one_attached :item_image

  def item_status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end
  
  validates :item_image, :name, :explanation, :genre_id, :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items
  
  validates :name, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :customer_id, presence: true
  validates :payment_method, presence: true
  validates :total_price, presence: true
  validates :postage, presence: true
  validates :status, presence: true
  
  
  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {waiting_for_payment: 0, confirmed_payment: 1, making: 2, shipping_preparation: 3, shipped: 4}
  
  def order_address_display
    "〒#{post_code} #{address}"
  end
  
  def order_price
    self.postage + self.total_price
  end
  
  
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :quantity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :price, presence: true
  validates :making_status, presence: true
  
  enum making_status:{not_ready: 0, pending: 1, making: 2, maked: 3}
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end 
  
  def create
    @genre = Genre.new(genre_params)
    if@genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end 
  
  def edit
    @genre = Genre.find(params[:id])
  end 
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @order = Order.all
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page])
  end 
  
  def new
    @item = Item.new
    @genres = Genre.pluck(:name, :id)
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.pluck(:name, :id)
      render new_admin_item_path
    end
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.pluck(:name, :id)
  end 
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end 
  
  
  private
  
  def item_params
    params.require(:item).permit(:item_image, :name, :explanation, :price, :genre_id, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    end
  end
end
 

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_signed_in.html.erb
<li><%= link_to '商品一覧', admin_items_path ,class:'nav-link text-light mx-6 px-4 btn btn-dark' %></li>
<li><%= link_to '会員一覧', admin_customers_path ,class:'nav-link text-light mx-4 px-4 btn btn-dark' %></li>
<li><%= link_to '注文履歴一覧', admin_path ,class:'nav-link text-light mx-7 px-4 btn btn-dark' %></li>
<li><%= link_to 'ジャンル一覧', admin_genres_path ,class:'nav-link text-light mx-4 px-4 btn btn-dark' %></li>
<li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete ,class:'nav-link text-light mx-6 px-4 btn btn-dark' %></li>

app/views/layouts/_customer_signed_in.html.erb
<li><%= link_to 'マイページ', customers_my_page_path ,class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to '商品一覧' , items_path, class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to 'カート', cart_items_path, class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>

app/views/layouts/_sign_out.html.erb
<li><%= link_to 'About', about_path ,class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to '商品一覧' , items_path, class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to '新規登録', new_customer_registration_path ,class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>
<li><%= link_to 'ログイン', new_customer_session_path ,class:'nav-link text-light mx-4 px-4 btn btn-info' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-4 bg-light border-bottom border-dark">
      <nav class="navbar navbar-expand-lg navbar-dark p-2 ">
        <div class="container">
          <div class="logo">
             <%= link_to root_path, class:'navbar-brand' do %><%= image_tag 'logo.png', :size => '250x200' %><% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <%= render 'layouts/customer_signed_in' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/admin_signed_in' %>
              <% else %>
                <%= render 'layouts/sign_out' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-10 col-lg-10 mx-auto">
            <p><%= flash[:notice] %></p>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="bg-light border-top border-dark pt-5 pb-5 mt-4">
      <div class="container">
        <div class="row">
          <div class="col-3 mx-auto">
            <h3>NAGANO CAKE</h3>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>